output "asg_name" {
  value = aws_autoscaling_group.this.name
}

output "security_group_id" {
  value       = aws_security_group.instance.id
  description = "ID of the instance security group"
}

output "instance_profile_name" {
  value       = aws_iam_instance_profile.instance.name
  description = "Name of the IAM instance profile"
}

output "config_bucket" {
  value       = aws_s3_bucket.config.bucket
  description = "S3 bucket name for instance config (also stores the binary at connect-arm64)"
}

output "config_s3_uri" {
  value       = "s3://${aws_s3_bucket.config.bucket}/config.json"
  description = "S3 URI for the instance config (auto-generated by Terraform)."
}
