name: Build and Release Spec-Tester

on:
  push:
    branches:
      - main
    paths:
      - "goclient/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Cross-Compile spec-tester
        run: |
          BINARY_NAME="spec-tester-${{ matrix.goos }}-${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o bin/${BINARY_NAME} ./goclient/cmd/spec-tester

      - name: Upload Temporary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/*
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          merge-multiple: true
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: goclient-${{ github.sha }}
          name: goclient ${{ github.sha }}
          files: release-artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
